import os

FACT_CHECK = "fact_check"

USERNAME = "sqma"
PASSWORD = "123456"

DEFAULT_MODEL_ENDPOINT = "http://10.0.1.194:7010/v1"
KG_BASE_URL = os.environ.get("KG_BASE") or "http://172.16.55.90:7625"
AUTH_URL = os.environ.get("AUTH_BASE") or "http://10.0.1.197:9992"
BASE_URL = os.environ.get("SERVER_BASE") or "http://172.17.0.1:3000/api/"

REFUTES_OPTION = ["UNSUPPORTED", "UNSUPPORT", "UNSUPPORTS", "UNSUPPORTE", "REFUTED", "REFUTES"]
SUPPORTS_OPTION = ["SUPPORTED", "SUPPORTS"]
UNSURE_OPTION = ["UNSURE", "UNRELATED"]

ERROR_RETRY_TIMES = 3